# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable updates for npm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/New_York"
    # Allow auto-merge for patch and minor updates
    target-branch: "master"
    # Group updates by type to reduce PR volume
    groups:
      # Group all patch updates together
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      # Group minor updates together  
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
      # Group security updates separately for priority
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
    # Enhanced settings for better automation
    open-pull-requests-limit: 20
    pull-request-branch-name:
      separator: "/"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # Enable reviewers (optional - can be customized)
    reviewers:
      - "grndszn"
    # Labels for organization
    labels:
      - "dependencies"
      - "automated"
    # Ignore specific packages if needed (uncomment and customize)
    # ignore:
    #   - dependency-name: "package-name"
    #     versions: ["1.x", "2.x"]
    
    # Allow both patch and minor version updates for security fixes
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    
    # Rebase strategy for keeping PRs up to date
    rebase-strategy: "auto"
    
  # Enable updates for GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/New_York"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    labels:
      - "github-actions"
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"

# Note: Auto-merge must be configured separately in repository settings
# or via GitHub CLI/API as it's not directly configurable in dependabot.yml
